# Generated by Django 6.0.1 on 2026-03-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermZaño', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='profesorID',
            new_name='professorID',
        ),
    ]
