# Generated by Django 6.0.1 on 2026-03-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('profesorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('amountPerCredits', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermZaño.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('totalAmount', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermZaño.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermZaño.professor')),
            ],
        ),
    ]
